name: medumba_app
description: "Medumba.AI - Apprendre le Medumba"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  shared_preferences: ^2.3.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  just_audio: ^0.9.40
  url_launcher: ^6.3.0
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_padded.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_padded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/data/
    - .env
