import 'package:flutter/material.dart';
import '../state/app_language.dart';
import '../theme/colors.dart';
import '../services/syllable_audio.dart';
import '../services/medumba_audio_service.dart';

class _Syl {
  final String syllable, ipa;
  const _Syl(this.syllable, this.ipa);
}

// Auto-generated from medumbaSyllables.js — 1147 entries
const _kSyllables = <_Syl>[
  _Syl('a', '[a]'),
  _Syl('a\'', '[ɑʔ]'),
  _Syl('α', '[ɑ]'),
  _Syl('αb', '[ɑb]'),
  _Syl('αm', '[ɑm]'),
  _Syl('αn', '[ɑn]'),
  _Syl('ba', '[ba]'),
  _Syl('bab', '[bab]'),
  _Syl('bad', '[bat]'),
  _Syl('bag', '[bak]'),
  _Syl('bal', '[bal]'),
  _Syl('bam', '[bam]'),
  _Syl('baŋ', '[baŋ]'),
  _Syl('ba\'', '[bɑʔ]'),
  _Syl('bα', '[bɑ]'),
  _Syl('bαb', '[bɑb]'),
  _Syl('bαg', '[bɑg]'),
  _Syl('bαm', '[bɑm]'),
  _Syl('bαn', '[bɑn]'),
  _Syl('bə', '[bœ], [bʉ]'),
  _Syl('bəd', '[bʉt]'),
  _Syl('bəl', '[bʉl]'),
  _Syl('bəm', '[bʉm]'),
  _Syl('bən', '[bʉn]'),
  _Syl('bə\'', '[bʉʔ]'),
  _Syl('be', '[bi]'),
  _Syl('beb', '[bib]'),
  _Syl('bed', '[bit]'),
  _Syl('bel', '[bil]'),
  _Syl('bem', '[bim]'),
  _Syl('ben', '[bin]'),
  _Syl('be\'', '[biʔ]'),
  _Syl('bɛ', '[bɛ]'),
  _Syl('bɛd', '[bɛt]'),
  _Syl('bɛl', '[bɛl]'),
  _Syl('bɛn', '[bɛn]'),
  _Syl('bi', '[bhi]'),
  _Syl('bia', '[bhia]'),
  _Syl('biaŋ', '[bhiaŋ]'),
  _Syl('biα', '[bhiɑ]'),
  _Syl('biαg', '[bhiɑk]'),
  _Syl('bib', '[bhib]'),
  _Syl('bid', '[bhit]'),
  _Syl('bil', '[bhil]'),
  _Syl('bin', '[bhin]'),
  _Syl('bo', '[bu]'),
  _Syl('bob', '[bub]'),
  _Syl('bod', '[but]'),
  _Syl('bol', '[bul]'),
  _Syl('bom', '[bum]'),
  _Syl('bon', '[bun]'),
  _Syl('bo\'', '[buʔ]'),
  _Syl('bɔ', '[bo]'),
  _Syl('bu', '[bhu]'),
  _Syl('bub', '[bhub]'),
  _Syl('bud', '[bhut]'),
  _Syl('bul', '[bhul]'),
  _Syl('bum', '[bhum]'),
  _Syl('bun', '[bhun]'),
  _Syl('bu\'', '[bhuʔ]'),
  _Syl('bʉ', '[bhʉ]'),
  _Syl('bʉaŋ', '[bhʉaŋ]'),
  _Syl('bʉα', '[bhʉɑ]'),
  _Syl('bʉn', '[bhʉn]'),
  _Syl('bʉ\'', '[bhʉʔ]'),
  _Syl('bwə', '[bhœ]'),
  _Syl('bwə\'', '[bhœʔ]'),
  _Syl('bwo', '[bhɔ]'),
  _Syl('bwog', '[bhɔg]'),
  _Syl('bwoŋ', '[bhɔŋ]'),
  _Syl('bwɔ', '[bho]'),
  _Syl('ca', '[tʃa]'),
  _Syl('cab', '[tʃab]'),
  _Syl('cag', '[tʃak]'),
  _Syl('cam', '[tʃam]'),
  _Syl('caŋ', '[tʃaŋ]'),
  _Syl('ca\'', '[tʃɑʔ]'),
  _Syl('cα', '[tʃɑ]'),
  _Syl('cαb', '[tʃɑb]'),
  _Syl('cαg', '[tʃɑk]'),
  _Syl('cαm', '[tʃɑm]'),
  _Syl('ce', '[tʃi]'),
  _Syl('ced', '[tʃit]'),
  _Syl('cel', '[tʃil]'),
  _Syl('cem', '[tʃim]'),
  _Syl('cə', '[tʃʉ]'),
  _Syl('cəb', '[tʃʉb]'),
  _Syl('cəd', '[tʃʉt]'),
  _Syl('cəl', '[tʃʉl]'),
  _Syl('cəm', '[tʃʉm]'),
  _Syl('cən', '[tʃʉn]'),
  _Syl('cə\'', '[tʃʉʔ]'),
  _Syl('cɛ', '[tʃɛ]'),
  _Syl('cɛd', '[tʃɛt]'),
  _Syl('cɛl', '[tʃɛl]'),
  _Syl('cɛn', '[tʃɛn]'),
  _Syl('co', '[tʃu]'),
  _Syl('cob', '[tʃub]'),
  _Syl('cog', '[tʃɔk]'),
  _Syl('com', '[tʃum]'),
  _Syl('coŋ', '[tʃɔŋ]'),
  _Syl('co\'', '[tʃuʔ]'),
  _Syl('cɔ', '[tʃo]'),
  _Syl('cu', '[tʃhu]'),
  _Syl('cub', '[tʃhub]'),
  _Syl('cul', '[tʃhul]'),
  _Syl('cum', '[tʃhum]'),
  _Syl('cu\'', '[tʃhuʔ]'),
  _Syl('cʉ', '[tʃhʉ]'),
  _Syl('cʉα', '[tʃhʉɑ]'),
  _Syl('cʉb', '[tʃhʉb]'),
  _Syl('cʉm', '[tʃhʉm]'),
  _Syl('cʉ\'', '[tʃhʉʔ]'),
  _Syl('cwa', '[tʃua]'),
  _Syl('cwad', '[tʃuat]'),
  _Syl('cwag', '[tʃuak]'),
  _Syl('cweb', '[tʃɥib]'),
  _Syl('cwed', '[tʃɥit]'),
  _Syl('cwel', '[tʃɥil]'),
  _Syl('cwem', '[tʃɥim]'),
  _Syl('cwen', '[tʃɥin]'),
  _Syl('cwe\'', '[tʃɥiʔ]'),
  _Syl('cwɛ', '[tʃuɛ]'),
  _Syl('cwɛd', '[tʃuɛt]'),
  _Syl('cwɛl', '[tʃuɛl]'),
  _Syl('cwɛn', '[tʃuɛn]'),
  _Syl('di', '[dzi]'),
  _Syl('dia', '[dzia]'),
  _Syl('diα', '[dziɑ]'),
  _Syl('din', '[dzin]'),
  _Syl('duα', '[dhuɑ]'),
  _Syl('du', '[dhu]'),
  _Syl('dub', '[dhub]'),
  _Syl('dud', '[dhut]'),
  _Syl('dul', '[dhul]'),
  _Syl('dum', '[dhum]'),
  _Syl('dun', '[dhun]'),
  _Syl('du\'', '[dhuʔ]'),
  _Syl('dʉ', '[dhʉ]'),
  _Syl('dʉb', '[dhʉb]'),
  _Syl('dʉd', '[dhʉt]'),
  _Syl('dʉl', '[dhʉl]'),
  _Syl('dʉm', '[dhʉm]'),
  _Syl('dʉn', '[dhʉn]'),
  _Syl('dʉ\'', '[dhʉʔ]'),
  _Syl('ɛn', '[ɛn]'),
  _Syl('ɛ\'', '[ɛʔ]'),
  _Syl('fa', '[fa]'),
  _Syl('fab', '[fab]'),
  _Syl('fad', '[fat]'),
  _Syl('fag', '[fak]'),
  _Syl('fal', '[fal]'),
  _Syl('fam', '[fam]'),
  _Syl('faŋ', '[faŋ]'),
  _Syl('fa\'', '[fɑʔ]'),
  _Syl('fα', '[fɑ]'),
  _Syl('fαb', '[fɑb]'),
  _Syl('fαn', '[fɑn]'),
  _Syl('fə', '[fhœ], [fʉ]'),
  _Syl('fəb', '[fʉb]'),
  _Syl('fəd', '[fʉt]'),
  _Syl('fəl', '[fʉl]'),
  _Syl('fəm', '[fʉm]'),
  _Syl('fən', '[fʉn]'),
  _Syl('fə\'', '[fhœʔ]'),
  _Syl('fe', '[fi]'),
  _Syl('feb', '[fib]'),
  _Syl('fel', '[fil]'),
  _Syl('fem', '[fim]'),
  _Syl('fe\'', '[fiʔ], [feʔ]'),
  _Syl('fɛ', '[fɛ]'),
  _Syl('fɛd', '[fɛt]'),
  _Syl('fɛl', '[fɛl]'),
  _Syl('fɛn', '[fɛn]'),
  _Syl('fi', '[fhi]'),
  _Syl('fia', '[fhia]'),
  _Syl('fiaŋ', '[fhiaŋ]'),
  _Syl('fiα', '[fhiɑ]'),
  _Syl('fiαg', '[fhiɑk]'),
  _Syl('fib', '[fhib]'),
  _Syl('fid', '[fhit]'),
  _Syl('fil', '[fhil]'),
  _Syl('fim', '[fhim]'),
  _Syl('fin', '[fhin]'),
  _Syl('fi\'', '[fhiʔ]'),
  _Syl('fo', '[fu]'),
  _Syl('fod', '[fud]'),
  _Syl('fog', '[fhɔk]'),
  _Syl('fom', '[fum]'),
  _Syl('fon', '[fun]'),
  _Syl('foŋ', '[fhɔŋ]'),
  _Syl('fu', '[fhu]'),
  _Syl('fub', '[fhub]'),
  _Syl('fu\'', '[fhuʔ]'),
  _Syl('fʉ', '[fhʉ]'),
  _Syl('fʉα', '[fhʉɑ]'),
  _Syl('fʉαg', '[fhʉɑk]'),
  _Syl('fʉd', '[fhʉt]'),
  _Syl('fʉl', '[fhʉl]'),
  _Syl('fʉn', '[fhʉn]'),
  _Syl('gə', '[gœ]'),
  _Syl('go', '[gu]'),
  _Syl('gha', '[gha]'),
  _Syl('ghab', '[ghab]'),
  _Syl('ghad', '[ghat]'),
  _Syl('ghag', '[ghak]'),
  _Syl('gham', '[gham]'),
  _Syl('ghaŋ', '[ghaŋ]'),
  _Syl('gha\'', '[ghɑʔ]'),
  _Syl('ghα', '[ghɑ]'),
  _Syl('ghαb', '[ghɑb]'),
  _Syl('ghə', '[ghʉ]'),
  _Syl('ghəb', '[ghʉb]'),
  _Syl('ghəd', '[ghʉt]'),
  _Syl('ghəl', '[ghʉl]'),
  _Syl('ghəm', '[ghʉm]'),
  _Syl('ghə\'', '[ghʉʔ]'),
  _Syl('gho', '[ghu]'),
  _Syl('ghob', '[ghub]'),
  _Syl('ghog', '[ghɔk]'),
  _Syl('ghom', '[ghum]'),
  _Syl('ghon', '[ghun]'),
  _Syl('gho\'', '[ghuʔ]'),
  _Syl('ghɔ', '[gho]'),
  _Syl('ghu', '[ghu]'),
  _Syl('ghua\'', '[ghuɑʔ]'),
  _Syl('ghuα', '[ghuɑ]'),
  _Syl('ghuαn', '[ghuɑn]'),
  _Syl('ghub', '[ghub]'),
  _Syl('ghu\'', '[ghuʔ]'),
  _Syl('ghʉ', '[ghʉ]'),
  _Syl('ghʉa', '[ghʉa]'),
  _Syl('ghʉaŋ', '[ghʉaŋ]'),
  _Syl('ghʉα', '[ghʉɑ]'),
  _Syl('ghʉd', '[ghʉt]'),
  _Syl('ghʉm', '[ghʉm]'),
  _Syl('ghʉn', '[ghʉn]'),
  _Syl('hα', '[hɑ]'),
  _Syl('həm', '[hʉm]'),
  _Syl('hɔ', '[ho]'),
  _Syl('ju', '[ȝu]'),
  _Syl('juad', '[ȝuat]'),
  _Syl('jub', '[ȝub]'),
  _Syl('jum', '[ȝum]'),
  _Syl('jun', '[ȝun]'),
  _Syl('ju\'', '[ȝuʔ]'),
  _Syl('jʉ', '[ȝʉ]'),
  _Syl('jʉα', '[ȝʉɑ]'),
  _Syl('jʉαg', '[ȝʉɑk]'),
  _Syl('jʉm', '[ȝʉm]'),
  _Syl('jʉ\'', '[ȝʉʔ]'),
  _Syl('ka', '[ka]'),
  _Syl('kab', '[kab]'),
  _Syl('kad', '[kat]'),
  _Syl('kag', '[kak]'),
  _Syl('kal', '[kal]'),
  _Syl('kam', '[kam]'),
  _Syl('kaŋ', '[kaŋ]'),
  _Syl('ka\'', '[kɑʔ]'),
  _Syl('kα', '[kɑ]'),
  _Syl('kαb', '[kɑb]'),
  _Syl('kαg', '[kɑk]'),
  _Syl('kαm', '[kɑm]'),
  _Syl('kαn', '[kɑn]'),
  _Syl('kə', '[kœ], [kʉ]'),
  _Syl('kəb', '[kʉb]'),
  _Syl('kəd', '[kʉt]'),
  _Syl('kəl', '[kʉl]'),
  _Syl('kəm', '[kʉm]'),
  _Syl('kə\'', '[kʉʔ]'),
  _Syl('ke', '[ki]'),
  _Syl('ked', '[kit]'),
  _Syl('kel', '[kil]'),
  _Syl('kem', '[kim]'),
  _Syl('ke\'', '[kiʔ]'),
  _Syl('kɛd', '[kɛt]'),
  _Syl('kɛl', '[kɛl]'),
  _Syl('ki', '[kxi]'),
  _Syl('kiα', '[kxiɑ]'),
  _Syl('kiαg', '[kxiɑk]'),
  _Syl('kib', '[kxib]'),
  _Syl('kin', '[kxin]'),
  _Syl('ki\'', '[kxiʔ]'),
  _Syl('ko', '[ku]'),
  _Syl('kob', '[kub]'),
  _Syl('kod', '[kud]'),
  _Syl('kog', '[kɔk]'),
  _Syl('kol', '[kul]'),
  _Syl('kom', '[kum]'),
  _Syl('koŋ', '[kɔŋ]'),
  _Syl('ko\'', '[kuʔ]'),
  _Syl('kɔ', '[ko]'),
  _Syl('ku', '[kxu]'),
  _Syl('kua\'', '[kxuɑʔ]'),
  _Syl('kuα', '[kxuɑ]'),
  _Syl('kuαn', '[kxuɑn]'),
  _Syl('kub', '[kxub]'),
  _Syl('kud', '[kxut]'),
  _Syl('kul', '[kxul]'),
  _Syl('kum', '[kxum]'),
  _Syl('kun', '[kxun]'),
  _Syl('ku\'', '[kxuʔ]'),
  _Syl('kʉ', '[kxʉ]'),
  _Syl('kʉα', '[kxʉɑ]'),
  _Syl('kʉd', '[kxʉt]'),
  _Syl('kʉl', '[kxʉl]'),
  _Syl('kʉm', '[kxʉm]'),
  _Syl('kʉ\'', '[kxʉʔ]'),
  _Syl('kwa', '[kua]'),
  _Syl('kwag', '[kuak]'),
  _Syl('kwaŋ', '[kuaŋ]'),
  _Syl('kwα', '[kuɑ]'),
  _Syl('kwαb', '[kuɑb]'),
  _Syl('kwe', '[kɥi]'),
  _Syl('kweb', '[kɥib]'),
  _Syl('kwem', '[kɥim]'),
  _Syl('kwe\'', '[kɥiʔ]'),
  _Syl('kwi', '[kxɥi]'),
  _Syl('kwia', '[kxɥia]'),
  _Syl('kwiaŋ', '[kxɥiaŋ]'),
  _Syl('kwiα', '[kxɥiɑ]'),
  _Syl('kwiαg', '[kxɥiɑk]'),
  _Syl('kwib', '[kxɥib]'),
  _Syl('kwid', '[kxɥit]'),
  _Syl('kwim', '[kxɥim]'),
  _Syl('kwin', '[kxɥin]'),
  _Syl('kwi\'', '[kxɥiʔ]'),
  _Syl('kwʉ', '[kxuʉ]'),
  _Syl('la', '[la]'),
  _Syl('lab', '[lab]'),
  _Syl('lad', '[lat]'),
  _Syl('lag', '[lak]'),
  _Syl('lal', '[lal]'),
  _Syl('lam', '[lam]'),
  _Syl('laŋ', '[laŋ]'),
  _Syl('la\'', '[lɑʔ]'),
  _Syl('lα', '[lɑ]'),
  _Syl('lαb', '[lɑb]'),
  _Syl('lαg', '[lɑg]'),
  _Syl('lαm', '[lɑm]'),
  _Syl('lαn', '[lɑn]'),
  _Syl('lə', '[lœ], [lʉ]'),
  _Syl('ləb', '[lʉb]'),
  _Syl('ləd', '[lʉt]'),
  _Syl('ləl', '[lʉl]'),
  _Syl('ləm', '[lʉm]'),
  _Syl('lən', '[lʉn]'),
  _Syl('lə\'', '[lʉʔ]'),
  _Syl('le', '[li]'),
  _Syl('led', '[lit]'),
  _Syl('lel', '[lil]'),
  _Syl('lem', '[lim]'),
  _Syl('le\'', '[liʔ]'),
  _Syl('lɛ', '[lɛ]'),
  _Syl('lɛd', '[lɛt]'),
  _Syl('lɛl', '[lɛl]'),
  _Syl('li', '[li]'),
  _Syl('lid', '[lit]'),
  _Syl('lin', '[lin]'),
  _Syl('lo', '[lu]'),
  _Syl('lob', '[lub]'),
  _Syl('log', '[lɔk]'),
  _Syl('lon', '[lun]'),
  _Syl('loŋ', '[lɔŋ]'),
  _Syl('lo\'', '[luʔ]'),
  _Syl('lɔ', '[lo]'),
  _Syl('ma', '[ma]'),
  _Syl('mad', '[mat]'),
  _Syl('mag', '[mak]'),
  _Syl('mal', '[mal]'),
  _Syl('maŋ', '[maŋ]'),
  _Syl('ma\'', '[mɑʔ]'),
  _Syl('mα', '[mɑ]'),
  _Syl('mαg', '[mɑk]'),
  _Syl('mαm', '[mɑm]'),
  _Syl('mba', '[mba]'),
  _Syl('mbab', '[mbab]'),
  _Syl('mbad', '[mbat]'),
  _Syl('mbag', '[mbak]'),
  _Syl('mbal', '[mbal]'),
  _Syl('mbam', '[mbam]'),
  _Syl('mbaŋ', '[mbaŋ]'),
  _Syl('mba\'', '[mbɑʔ]'),
  _Syl('mbα', '[mbɑ]'),
  _Syl('mbαb', '[mbɑb]'),
  _Syl('mbαg', '[mbɑk]'),
  _Syl('mbαm', '[mbɑm]'),
  _Syl('mbαn', '[mbɑn]'),
  _Syl('mbə', '[mbʉ]'),
  _Syl('mbəd', '[mbʉt]'),
  _Syl('mbəl', '[mbʉl]'),
  _Syl('mbəm', '[mbʉm]'),
  _Syl('mbə\'', '[mbʉʔ]'),
  _Syl('mbe', '[mbi]'),
  _Syl('mbed', '[mbit]'),
  _Syl('mbel', '[mbil]'),
  _Syl('mbem', '[mbim]'),
  _Syl('mben', '[mbin]'),
  _Syl('mbe\'', '[mbiʔ]'),
  _Syl('mbɛ', '[mbɛ]'),
  _Syl('mbɛd', '[mbɛt]'),
  _Syl('mbɛl', '[mbɛl]'),
  _Syl('mbɛn', '[mbɛn]'),
  _Syl('mbi', '[mbhi]'),
  _Syl('mbia', '[mbhia]'),
  _Syl('mbia\'', '[mbhiaʔ]'),
  _Syl('mbiα', '[mbhiɑ]'),
  _Syl('mbiαg', '[mbhiɑk]'),
  _Syl('mbid', '[mbhit]'),
  _Syl('mbil', '[mbhil]'),
  _Syl('mbi\'', '[mbhiʔ]'),
  _Syl('mbo', '[mbu]'),
  _Syl('mbob', '[mbub]'),
  _Syl('mbod', '[mbut]'),
  _Syl('mboŋ', '[mbɔŋ]'),
  _Syl('mbo\'', '[mbuʔ]'),
  _Syl('mbu', '[mbhu]'),
  _Syl('mbub', '[mbhub]'),
  _Syl('mbul', '[mbhul]'),
  _Syl('mbum', '[mbhum]'),
  _Syl('mbun', '[mbhun]'),
  _Syl('mbu\'', '[mbhuʔ]'),
  _Syl('mbʉ', '[mbhʉ]'),
  _Syl('mbʉα', '[mbhʉɑ]'),
  _Syl('mbʉαg', '[mbhʉɑk]'),
  _Syl('mbʉm', '[mbhʉm]'),
  _Syl('mbʉn', '[mbhʉn]'),
  _Syl('mbʉ\'', '[mbhʉʔ]'),
  _Syl('mbwə', '[mbhœ]'),
  _Syl('mbwə\'', '[mbhœʔ]'),
  _Syl('mbwog', '[mbhɔk]'),
  _Syl('mbwoŋ', '[mbhɔŋ]'),
  _Syl('mbwɔ', '[mbho]'),
  _Syl('mə', '[mœ], [mʉ]'),
  _Syl('məm', '[mʉm]'),
  _Syl('mən', '[mʉn]'),
  _Syl('mə\'', '[mʉʔ]'),
  _Syl('me', '[mi]'),
  _Syl('mem', '[mim]'),
  _Syl('me\'', '[miʔ]'),
  _Syl('mfa', '[ɱva]'),
  _Syl('mfad', '[ɱvat]'),
  _Syl('mfag', '[ɱvak]'),
  _Syl('mfal', '[ɱval]'),
  _Syl('mfam', '[ɱvam]'),
  _Syl('mfaŋ', '[ɱvaŋ]'),
  _Syl('mfa\'', '[ɱvɑʔ]'),
  _Syl('mfα', '[mvɑ]'),
  _Syl('mfαb', '[ɱvɑb]'),
  _Syl('mfαn', '[ɱvɑn]'),
  _Syl('mfə', '[ɱfhœ], [ɱvœ], [ɱvʉ]'),
  _Syl('mfəb', '[ɱvʉb]'),
  _Syl('mfəd', '[ɱvʉt]'),
  _Syl('mfəl', '[ɱvʉl]'),
  _Syl('mfəm', '[ɱvʉm]'),
  _Syl('mfən', '[ɱvʉn]'),
  _Syl('mfə\'', '[ɱfhœʔ]'),
  _Syl('mfe', '[ɱvi]'),
  _Syl('mfeb', '[ɱvib]'),
  _Syl('mfed', '[ɱvit]'),
  _Syl('mfel', '[ɱvil]'),
  _Syl('mfem', '[ɱvim]'),
  _Syl('mfe\'', '[ɱviʔ]'),
  _Syl('mfɛ', '[ɱvɛ]'),
  _Syl('mfɛd', '[ɱvɛt]'),
  _Syl('mfɛl', '[ɱvɛl]'),
  _Syl('mfɛn', '[ɱvɛ]'),
  _Syl('mfi', '[ɱfhi]'),
  _Syl('mfia', '[ɱfhia]'),
  _Syl('mfiα', '[ɱfhiɑ]'),
  _Syl('mfiαg', '[ɱfhiɑg]'),
  _Syl('mfid', '[ɱfhid]'),
  _Syl('mfil', '[ɱfhil]'),
  _Syl('mfim', '[ɱfhim]'),
  _Syl('mfin', '[ɱfhin]'),
  _Syl('mfi\'', '[ɱfhiʔ]'),
  _Syl('mfo', '[ɱvo]'),
  _Syl('mfod', '[ɱvot]'),
  _Syl('mfog', '[ɱfhɔk]'),
  _Syl('mfol', '[ɱvol]'),
  _Syl('mfom', '[ɱvom]'),
  _Syl('mfoŋ', '[ɱfhɔŋ]'),
  _Syl('mfɔ', '[ɱvo]'),
  _Syl('mfu', '[ɱfhu]'),
  _Syl('mfub', '[ɱfhub]'),
  _Syl('mfu\'', '[ɱfhuʔ]'),
  _Syl('mfʉ', '[ɱfhʉ]'),
  _Syl('mfʉα', '[ɱfhʉɑ]'),
  _Syl('mfʉαg', '[ɱfhʉɑk]'),
  _Syl('mfʉd', '[ɱfhʉt]'),
  _Syl('mfʉl', '[ɱfhʉl]'),
  _Syl('mfʉm', '[ɱfhʉm]'),
  _Syl('mfʉn', '[ɱfhʉn]'),
  _Syl('mi', '[mi]'),
  _Syl('miα', '[miɑ]'),
  _Syl('miαg', '[miɑk]'),
  _Syl('mib', '[mib]'),
  _Syl('mid', '[mit]'),
  _Syl('mil', '[mil]'),
  _Syl('min', '[min]'),
  _Syl('mi\'', '[miʔ]'),
  _Syl('mo', '[mu]'),
  _Syl('mom', '[mum]'),
  _Syl('mo\'', '[muʔ]'),
  _Syl('mɔ', '[mo]'),
  _Syl('mu', '[mu]'),
  _Syl('mub', '[mub]'),
  _Syl('mud', '[mut]'),
  _Syl('mul', '[mul]'),
  _Syl('mvaŋ', '[ɱvaŋ]'),
  _Syl('mvə', '[ɱvhœ]'),
  _Syl('mvə\'', '[ɱvʉʔ]'),
  _Syl('mvɛd', '[ɱvɛt]'),
  _Syl('mvɛn', '[ɱvɛn]'),
  _Syl('mvog', '[ɱvhɔk]'),
  _Syl('mvʉ', '[ɱvhʉ]'),
  _Syl('na', '[na]'),
  _Syl('nam', '[nam]'),
  _Syl('naŋ', '[naŋ]'),
  _Syl('na\'', '[naʔ]'),
  _Syl('nα', '[nɑ]'),
  _Syl('nαb', '[nɑb]'),
  _Syl('nαn', '[nɑn]'),
  _Syl('nca', '[ntʃa]'),
  _Syl('ncab', '[ntʃab]'),
  _Syl('ncag', '[ntʃak]'),
  _Syl('ncam', '[ntʃam]'),
  _Syl('ncaŋ', '[ntʃaŋ]'),
  _Syl('nca\'', '[ntʃɑʔ]'),
  _Syl('ncα', '[ntʃɑ]'),
  _Syl('ncαb', '[ntʃɑb]'),
  _Syl('ncαg', '[ntʃɑg]'),
  _Syl('ncαm', '[ntʃɑm]'),
  _Syl('ncə', '[ntʃʉ]'),
  _Syl('ncəb', '[ntʃʉb]'),
  _Syl('ncəd', '[ntʃʉt]'),
  _Syl('ncəl', '[ntʃʉl]'),
  _Syl('ncəm', '[ntʃʉm]'),
  _Syl('ncə\'', '[ntʃʉʔ]'),
  _Syl('nce', '[ntʃi]'),
  _Syl('nced', '[ntʃit]'),
  _Syl('ncel', '[ntʃil]'),
  _Syl('ncem', '[ntʃim]'),
  _Syl('nce\'', '[ntʃiʔ]'),
  _Syl('ncɛ', '[ntʃɛ]'),
  _Syl('ncɛd', '[ntʃɛt]'),
  _Syl('ncɛl', '[ntʃɛl]'),
  _Syl('ncɛn', '[ntʃɛn]'),
  _Syl('nco', '[ntʃu]'),
  _Syl('ncob', '[ntʃub]'),
  _Syl('ncog', '[ntʃɔk]'),
  _Syl('ncom', '[ntʃum]'),
  _Syl('ncoŋ', '[ntʃɔŋ]'),
  _Syl('nco\'', '[ntʃuʔ]'),
  _Syl('ncu', '[ntʃhu]'),
  _Syl('ncua\'', '[ntʃhuaʔ]'),
  _Syl('ncuα', '[ntʃhuɑ]'),
  _Syl('ncub', '[ntʃhub]'),
  _Syl('ncum', '[ntʃhm]'),
  _Syl('ncu\'', '[ntʃhuʔ]'),
  _Syl('ncʉ', '[ntʃhʉ]'),
  _Syl('ncʉa', '[ntʃhʉa]'),
  _Syl('ncʉaŋ', '[ntʃhʉaŋ]'),
  _Syl('ncʉα', '[ntʃhʉɑ]'),
  _Syl('ncʉαg', '[ntʃhɑk]'),
  _Syl('ncʉb', '[ntʃhʉb]'),
  _Syl('ncʉm', '[ntʃhʉm]'),
  _Syl('ncʉ\'', '[ntʃhʉʔ]'),
  _Syl('ncwa', '[ntʃua]'),
  _Syl('ncwad', '[ntʃuad]'),
  _Syl('ncwe', '[ntʃɥi]'),
  _Syl('ncweb', '[ntʃɥib]'),
  _Syl('ncwed', '[ntʃɥit]'),
  _Syl('ncwel', '[ntʃɥil]'),
  _Syl('ncwem', '[ntʃɥim]'),
  _Syl('ncwe\'', '[ntʃɥiʔ]'),
  _Syl('nda', '[nda]'),
  _Syl('ndab', '[ndab]'),
  _Syl('ndad', '[ndat]'),
  _Syl('ndag', '[ndak]'),
  _Syl('ndal', '[ndal]'),
  _Syl('ndam', '[ndam]'),
  _Syl('ndaŋ', '[ndaŋ]'),
  _Syl('nda\'', '[ndɑʔ]'),
  _Syl('ndα', '[ndɑ]'),
  _Syl('ndαb', '[ndɑb]'),
  _Syl('ndαg', '[ndɑk]'),
  _Syl('ndαm', '[ndɑm]'),
  _Syl('ndαn', '[ndɑn]'),
  _Syl('ndə', '[ndʉ]'),
  _Syl('ndəb', '[ndʉb]'),
  _Syl('ndəd', '[ndʉt]'),
  _Syl('ndəl', '[ndʉl]'),
  _Syl('ndəm', '[ndʉm]'),
  _Syl('ndə\'', '[ndʉʔ]'),
  _Syl('nde', '[ndi]'),
  _Syl('ndeb', '[ndib]'),
  _Syl('nded', '[ndit]'),
  _Syl('ndel', '[ndil]'),
  _Syl('ndem', '[ndim]'),
  _Syl('nde\'', '[ndiʔ]'),
  _Syl('ndɛ', '[ndɛ]'),
  _Syl('ndɛd', '[ndɛt]'),
  _Syl('ndɛl', '[ndɛl]'),
  _Syl('ndɛn', '[ndɛn]'),
  _Syl('ndo', '[ndu]'),
  _Syl('ndob', '[ndub]'),
  _Syl('ndod', '[ndut]'),
  _Syl('ndon', '[ndun]'),
  _Syl('ndoŋ', '[ndɔŋ]'),
  _Syl('ndo\'', '[nduʔ]'),
  _Syl('ndɔ', '[ndo]'),
  _Syl('ndu', '[ndhu]'),
  _Syl('ndub', '[ndhub]'),
  _Syl('ndud', '[ndhut]'),
  _Syl('ndul', '[ndhul]'),
  _Syl('ndum', '[ndhum]'),
  _Syl('ndun', '[ndhun]'),
  _Syl('ndu\'', '[ndhuʔ]'),
  _Syl('ndʉ', '[ndhʉ]'),
  _Syl('ndʉb', '[ndhʉb]'),
  _Syl('ndʉm', '[ndhʉb]'),
  _Syl('ndʉ\'', '[ndhʉʔ]'),
  _Syl('nə', '[nœ], [nʉ]'),
  _Syl('nə\'', '[nʉʔ]'),
  _Syl('nɛ', '[nɛ]'),
  _Syl('nɛn', '[nɛn]'),
  _Syl('nga', '[ŋga]'),
  _Syl('ngab', '[ŋga]'),
  _Syl('ngad', '[ŋgat]'),
  _Syl('ngag', '[ŋgak]'),
  _Syl('ngal', '[ŋgal]'),
  _Syl('ngam', '[ŋgam]'),
  _Syl('ngaŋ', '[ŋgaŋ]'),
  _Syl('nga\'', '[ŋgɑʔ]'),
  _Syl('ngαb', '[ŋgɑb]'),
  _Syl('ngαm', '[ŋgɑm]'),
  _Syl('ngαn', '[ŋgɑn]'),
  _Syl('ngə', '[ŋgœ], [ŋgʉ]'),
  _Syl('ngəb', '[ŋgʉb]'),
  _Syl('ngəd', '[ŋgʉt]'),
  _Syl('ngəl', '[ŋgʉl]'),
  _Syl('ngəm', '[ŋgʉm]'),
  _Syl('ngə\'', '[ŋgʉʔ]'),
  _Syl('ngo', '[ŋgu]'),
  _Syl('ngob', '[ŋgub]'),
  _Syl('ngom', '[ŋgum]'),
  _Syl('ngon', '[ŋgun]'),
  _Syl('ngoŋ', '[ŋgɔŋ]'),
  _Syl('ngo\'', '[ŋguʔ]'),
  _Syl('ngɔ', '[ŋgo]'),
  _Syl('ngu', '[ŋghu]'),
  _Syl('nguα', '[ŋghuɑ]'),
  _Syl('nguαn', '[ŋghuɑn]'),
  _Syl('ngub', '[ŋghub]'),
  _Syl('ngum', '[ŋghum]'),
  _Syl('ngu\'', '[ŋghuʔ]'),
  _Syl('ngʉ', '[ŋghʉ]'),
  _Syl('ngʉα', '[ŋghʉɑ]'),
  _Syl('ngʉm', '[ŋghʉm]'),
  _Syl('ngʉn', '[ŋghʉn]'),
  _Syl('ngʉ\'', '[ŋghʉʔ]'),
  _Syl('ngwa', '[ŋgua]'),
  _Syl('ngwad', '[ŋguat]'),
  _Syl('ngwag', '[ŋguak]'),
  _Syl('ngwal', '[ŋgual]'),
  _Syl('ngwaŋ', '[ŋguaŋ]'),
  _Syl('ni', '[ni]'),
  _Syl('njα', '[ndȝɑ]'),
  _Syl('njαb', '[ndȝɑb]'),
  _Syl('njαg', '[ndȝɑk]'),
  _Syl('njαm', '[ndȝɑm]'),
  _Syl('njo', '[ndȝu]'),
  _Syl('njob', '[ndȝub]'),
  _Syl('njod', '[ndȝut]'),
  _Syl('njog', '[ndȝɔk]'),
  _Syl('njol', '[ndȝul]'),
  _Syl('njom', '[ndȝum]'),
  _Syl('njoŋ', '[ndȝɔŋ]'),
  _Syl('njo\'', '[ndȝuʔ]'),
  _Syl('njɔ', '[ndȝo]'),
  _Syl('nju', '[nȝu]'),
  _Syl('njub', '[nȝub]'),
  _Syl('njum', '[nȝum]'),
  _Syl('njun', '[nȝun]'),
  _Syl('nju\'', '[nȝuʔ]'),
  _Syl('njʉ', '[nȝʉ]'),
  _Syl('njʉα', '[nȝʉɑ]'),
  _Syl('njʉαg', '[nȝʉɑk]'),
  _Syl('njʉm', '[nȝʉm]'),
  _Syl('njʉ\'', '[nȝʉʔ]'),
  _Syl('njwe', '[ndȝui]'),
  _Syl('njwed', '[ndȝuit]'),
  _Syl('njwel', '[ndȝuil]'),
  _Syl('njwem', '[ndȝuim]'),
  _Syl('njwe\'', '[ndȝuiʔ]'),
  _Syl('njwɛ', '[ndȝuɛ]'),
  _Syl('njwɛd', '[ndȝuɛt]'),
  _Syl('njwɛl', '[ndȝuɛl]'),
  _Syl('njwɛn', '[ndȝuɛn]'),
  _Syl('nka', '[ŋka]'),
  _Syl('nkab', '[ŋkab]'),
  _Syl('nkad', '[ŋkat]'),
  _Syl('nkag', '[ŋkak]'),
  _Syl('nkal', '[ŋkal]'),
  _Syl('nkam', '[ŋkam]'),
  _Syl('nkaŋ', '[ŋkaŋ]'),
  _Syl('nka\'', '[ŋkɑʔ]'),
  _Syl('nkα', '[ŋkɑ]'),
  _Syl('nkαb', '[ŋkɑb]'),
  _Syl('nkαg', '[ŋkɑk]'),
  _Syl('nkαm', '[ŋkɑm]'),
  _Syl('nkαn', '[ŋkɑn]'),
  _Syl('nkə', '[ŋkœ], [ŋkʉ]'),
  _Syl('nkəb', '[ŋkʉb]'),
  _Syl('nkəd', '[ŋkʉt]'),
  _Syl('nkəl', '[ŋkʉl]'),
  _Syl('nkəm', '[ŋkʉm]'),
  _Syl('nkə\'', '[ŋkʉʔ]'),
  _Syl('nke', '[ŋki]'),
  _Syl('nked', '[ŋkit]'),
  _Syl('nkel', '[ŋkil]'),
  _Syl('nkem', '[ŋkim]'),
  _Syl('nke\'', '[ŋkiʔ]'),
  _Syl('nkioŋ', '[ŋkiɔŋ]'),
  _Syl('nkob', '[ŋkub]'),
  _Syl('nkod', '[ŋkut]'),
  _Syl('nkog', '[ŋkɔk]'),
  _Syl('nkol', '[ŋkul]'),
  _Syl('nkom', '[ŋkum]'),
  _Syl('nkoŋ', '[ŋkɔŋ]'),
  _Syl('nko\'', '[ŋkuʔ]'),
  _Syl('nkɔ', '[ŋko]'),
  _Syl('nku', '[ŋkxu]'),
  _Syl('nkuα', '[ŋkxuɑ]'),
  _Syl('nkub', '[ŋkxub]'),
  _Syl('nkud', '[ŋkxut]'),
  _Syl('nkul', '[ŋkxul]'),
  _Syl('nkum', '[ŋkxum]'),
  _Syl('nkun', '[ŋkxun]'),
  _Syl('nku\'', '[ŋkxuʔ]'),
  _Syl('nkʉ', '[ŋkxʉ]'),
  _Syl('nkʉα', '[ŋkxʉɑ]'),
  _Syl('nkʉd', '[ŋkxʉt]'),
  _Syl('nkʉl', '[ŋkxʉl]'),
  _Syl('nkʉm', '[ŋkxʉm]'),
  _Syl('nkʉn', '[ŋkxʉn]'),
  _Syl('nkʉ\'', '[ŋkxʉʔ]'),
  _Syl('nkwa', '[ŋkua]'),
  _Syl('nkwad', '[ŋkuat]'),
  _Syl('nkwag', '[ŋkuak]'),
  _Syl('nkwα', '[ŋkuɑ]'),
  _Syl('nkwαb', '[ŋkuɑb]'),
  _Syl('nkwe', '[ŋkɥi]'),
  _Syl('nkweb', '[ŋkɥib]'),
  _Syl('nkwem', '[ŋkɥim]'),
  _Syl('nkwe\'', '[ŋkɥiʔ]'),
  _Syl('nkwi', '[ŋkxɥi]'),
  _Syl('nkwia', '[ŋkxɥia]'),
  _Syl('nkwiaŋ', '[ŋkxɥiaŋ]'),
  _Syl('nkwiα', '[ŋkxɥia]'),
  _Syl('nkwiαg', '[ŋkxɥiak]'),
  _Syl('nkwib', '[ŋkxɥib]'),
  _Syl('nkwid', '[ŋkxɥit]'),
  _Syl('nkwil', '[ŋkxɥil]'),
  _Syl('nkwim', '[ŋkxɥim]'),
  _Syl('nkwin', '[ŋkxɥin]'),
  _Syl('nkwi\'', '[ŋkxɥiʔ]'),
  _Syl('nkwʉ', '[ŋkxuʉ]'),
  _Syl('no', '[nu]'),
  _Syl('nod', '[nut]'),
  _Syl('nog', '[nɔk]'),
  _Syl('nol', '[nul]'),
  _Syl('no\'', '[nuʔ]'),
  _Syl('nɔ', '[no]'),
  _Syl('nsa', '[nza]'),
  _Syl('nsab', '[nzab]'),
  _Syl('nsad', '[nzat]'),
  _Syl('nsag', '[nzag]'),
  _Syl('nsal', '[nzal]'),
  _Syl('nsam', '[nzam]'),
  _Syl('nsaŋ', '[nzaŋ]'),
  _Syl('nsa\'', '[nzaʔ]'),
  _Syl('nsα', '[nzɑ]'),
  _Syl('nsαb', '[nzɑb]'),
  _Syl('nsαg', '[nzɑk]'),
  _Syl('nsαm', '[nzɑm]'),
  _Syl('nsə', '[nshœ], [nzʉ]'),
  _Syl('nsəb', '[nzʉb]'),
  _Syl('nsəd', '[nzʉt]'),
  _Syl('nsəl', '[nzʉl]'),
  _Syl('nsəm', '[nzʉm]'),
  _Syl('nsə\'', '[nshœʔ], [nzʉʔ]'),
  _Syl('nse', '[nzi]'),
  _Syl('nseb', '[nzib]'),
  _Syl('nsem', '[nzim]'),
  _Syl('nse\'', '[nziʔ]'),
  _Syl('nsɛ', '[nzɛ]'),
  _Syl('nsɛn', '[nzɛn]'),
  _Syl('nsi', '[nshi]'),
  _Syl('nsia', '[nshia]'),
  _Syl('nsiaŋ', '[nshiaŋ]'),
  _Syl('nsiα', '[nshiɑ]'),
  _Syl('nsiαg', '[nshiɑk]'),
  _Syl('nsin', '[nshin]'),
  _Syl('nso', '[nzu]'),
  _Syl('nsob', '[nzub]'),
  _Syl('nsog', '[nshɔk]'),
  _Syl('nsom', '[nzum]'),
  _Syl('nsoŋ', '[nshɔŋ]'),
  _Syl('nsɔ', '[nzo]'),
  _Syl('nswa', '[nzua]'),
  _Syl('nswad', '[nzuat]'),
  _Syl('nswal', '[nzual]'),
  _Syl('nswə', '[nshuœ]'),
  _Syl('nswə\'', '[nshuœʔ]'),
  _Syl('nswɛ', '[nzuɛ]'),
  _Syl('nswɛd', '[nzuɛt]'),
  _Syl('nswɛl', '[nzuɛl]'),
  _Syl('nswɛn', '[nzuɛn]'),
  _Syl('nshu', '[nʃu]'),
  _Syl('nshun', '[nʃun]'),
  _Syl('nshu\'', '[nʃuʔ]'),
  _Syl('nshʉ', '[nʃʉ]'),
  _Syl('nshʉn', '[nʃʉn]'),
  _Syl('nshʉ\'', '[nʃʉʔ]'),
  _Syl('nta', '[nta]'),
  _Syl('ntab', '[ntab]'),
  _Syl('ntad', '[ntat]'),
  _Syl('ntag', '[ntak]'),
  _Syl('ntam', '[ntam]'),
  _Syl('ntaŋ', '[ntaŋ]'),
  _Syl('nta\'', '[ntaʔ]'),
  _Syl('ntα', '[ntɑ]'),
  _Syl('ntαb', '[ntɑb]'),
  _Syl('ntαg', '[ntɑk]'),
  _Syl('ntαm', '[ntɑm]'),
  _Syl('ntαn', '[ntɑn]'),
  _Syl('ntə', '[ntʉ]'),
  _Syl('ntəd', '[ntʉt]'),
  _Syl('ntəm', '[ntʉm]'),
  _Syl('ntən', '[ntʉn]'),
  _Syl('ntə\'', '[ntʉʔ]'),
  _Syl('ntɛ', '[ntɛ]'),
  _Syl('ntɛd', '[ntɛt]'),
  _Syl('ntɛl', '[ntɛl]'),
  _Syl('ntɛn', '[ntɛn]'),
  _Syl('ntiα', '[ntiɑ]'),
  _Syl('ntiαg', '[ntiɑk]'),
  _Syl('nto', '[ntu]'),
  _Syl('ntob', '[ntub]'),
  _Syl('ntod', '[ntut]'),
  _Syl('ntog', '[ntɔk]'),
  _Syl('ntol', '[ntul]'),
  _Syl('ntom', '[ntum]'),
  _Syl('nton', '[ntun]'),
  _Syl('nto\'', '[ntuʔ]'),
  _Syl('ntɔ', '[nto]'),
  _Syl('ntu', '[nthu]'),
  _Syl('ntub', '[nthub]'),
  _Syl('ntud', '[nthut]'),
  _Syl('ntul', '[nthul]'),
  _Syl('ntum', '[nthum]'),
  _Syl('ntun', '[nthun]'),
  _Syl('ntu\'', '[nthuʔ]'),
  _Syl('ntʉ', '[nthʉ]'),
  _Syl('ntʉn', '[nthʉn]'),
  _Syl('ntʉ\'', '[nthʉʔ]'),
  _Syl('ntsə', '[ntsœ]'),
  _Syl('ntsə\'', '[ntsœʔ]'),
  _Syl('ntsi', '[ntsi]'),
  _Syl('ntsia', '[ntsia]'),
  _Syl('ntsiaŋ', '[ntsiaŋ]'),
  _Syl('ntsiα', '[ntsiɑ]'),
  _Syl('ntsiαg', '[ntsiɑg]'),
  _Syl('ntswə', '[ntsuœ]'),
  _Syl('ntswə\'', '[ntsuœʔ]'),
  _Syl('nu', '[nu]'),
  _Syl('nud', '[nut]'),
  _Syl('nul', '[nul]'),
  _Syl('nu\'', '[nuʔ]'),
  _Syl('nʉ', '[nʉ]'),
  _Syl('nʉn', '[nʉn]'),
  _Syl('nʉ\'', '[nʉʔ]'),
  _Syl('nzə', '[nzhœ]'),
  _Syl('nzə\'', '[nzhœʔ]'),
  _Syl('nzi', '[nzhi]'),
  _Syl('nzia', '[nzhia]'),
  _Syl('nziag', '[nzhiak]'),
  _Syl('nzib', '[nzhib]'),
  _Syl('nzid', '[nzhit]'),
  _Syl('nzil', '[nzhil]'),
  _Syl('nzim', '[nzhim]'),
  _Syl('nzin', '[zhi]'),
  _Syl('nzi\'', '[nzhiʔ]'),
  _Syl('nzwə', '[nzhuœ]'),
  _Syl('nzwə\'', '[nzhuœʔ]'),
  _Syl('nzwi', '[nzhɥi]'),
  _Syl('nzwiaŋ', '[nzhɥiaŋ]'),
  _Syl('nzwiα', '[nzhɥiɑ]'),
  _Syl('nzwiαg', '[nzhɥiɑk]'),
  _Syl('nzwid', '[nzhɥit]'),
  _Syl('nzwil', '[nzhɥil]'),
  _Syl('nzwim', '[nzhɥi]'),
  _Syl('nzwi\'', '[nzhɥiʔ]'),
  _Syl('ŋa', '[ŋa]'),
  _Syl('ŋad', '[ŋad]'),
  _Syl('ŋag', '[ŋak]'),
  _Syl('ŋal', '[ŋal]'),
  _Syl('ŋam', '[ŋam]'),
  _Syl('ŋa\'', '[ŋaʔ]'),
  _Syl('ŋα', '[ŋɑ]'),
  _Syl('ŋαb', '[ŋɑb]'),
  _Syl('ŋə', '[ŋœ]'),
  _Syl('ŋu', '[ŋu]'),
  _Syl('ŋu\'', '[ŋuʔ]'),
  _Syl('ŋʉ', '[ŋʉ]'),
  _Syl('ŋwa', '[ŋua]'),
  _Syl('ŋwad', '[ŋuat]'),
  _Syl('ŋwag', '[ŋuak]'),
  _Syl('ŋwal', '[ŋual]'),
  _Syl('ŋwaŋ', '[ŋuaŋ]'),
  _Syl('ŋwa\'', '[ŋuaʔ]'),
  _Syl('ŋwα', '[ŋuɑ]'),
  _Syl('ŋwi', '[ŋɥi]'),
  _Syl('ŋwid', '[ŋɥit]'),
  _Syl('ŋwil', '[ŋɥil]'),
  _Syl('ŋwin', '[ŋɥin]'),
  _Syl('ŋwʉ', '[ŋuʉ]'),
  _Syl('o', '[u]'),
  _Syl('ɔ', '[o]'),
  _Syl('ɔ\'', '[oʔ]'),
  _Syl('sa', '[sa]'),
  _Syl('sab', '[sab]'),
  _Syl('sad', '[sat]'),
  _Syl('sag', '[sak]'),
  _Syl('sal', '[sal]'),
  _Syl('sam', '[sam]'),
  _Syl('saŋ', '[saŋ]'),
  _Syl('sa\'', '[saʔ]'),
  _Syl('sα', '[sɑ]'),
  _Syl('sαb', '[sɑb]'),
  _Syl('sαg', '[sɑk]'),
  _Syl('sαm', '[sɑm], [sɔm]'),
  _Syl('sαn', '[sɑn]'),
  _Syl('sə', '[shœ], [sʉ]'),
  _Syl('səb', '[sʉb]'),
  _Syl('səd', '[sʉt]'),
  _Syl('səl', '[sʉl]'),
  _Syl('səm', '[sʉm]'),
  _Syl('sən', '[sʉn]'),
  _Syl('sə\'', '[shœʔ], [sʉʔ]'),
  _Syl('se', '[si]'),
  _Syl('seb', '[sib]'),
  _Syl('sem', '[sim]'),
  _Syl('se\'', '[siʔ]'),
  _Syl('sɛ', '[sɛ]'),
  _Syl('sɛn', '[sɛn]'),
  _Syl('si', '[shi]'),
  _Syl('sia', '[shia]'),
  _Syl('siaŋ', '[shiaŋ]'),
  _Syl('siα', '[shiɑ]'),
  _Syl('siαg', '[shiɑk]'),
  _Syl('so', '[su]'),
  _Syl('sob', '[sub]'),
  _Syl('sog', '[shɔk]'),
  _Syl('soŋ', '[shɔŋ]'),
  _Syl('sɔ', '[so]'),
  _Syl('su', '[su]'),
  _Syl('sub', '[sub]'),
  _Syl('shu', '[ʃu]'),
  _Syl('shud', '[ʃut]'),
  _Syl('shu\'', '[ʃuʔ]'),
  _Syl('shʉ', '[ʃʉ]'),
  _Syl('shʉ\'', '[ʃʉʔ]'),
  _Syl('swa', '[sua]'),
  _Syl('swad', '[suat]'),
  _Syl('swal', '[sual]'),
  _Syl('swə', '[shuœ]'),
  _Syl('swə\'', '[shuœʔ]'),
  _Syl('swɛ', '[suɛ]'),
  _Syl('swɛd', '[suɛt]'),
  _Syl('swɛl', '[suɛl]'),
  _Syl('swɛn', '[suɛn]'),
  _Syl('ta', '[ta]'),
  _Syl('tab', '[tab]'),
  _Syl('tad', '[tat]'),
  _Syl('tag', '[tak]'),
  _Syl('tal', '[tal]'),
  _Syl('tam', '[tam]'),
  _Syl('taŋ', '[taŋ]'),
  _Syl('ta\'', '[taʔ]'),
  _Syl('tα', '[tɑ]'),
  _Syl('tαb', '[tɑb]'),
  _Syl('tαg', '[tɑk]'),
  _Syl('tαm', '[tɑm]'),
  _Syl('tαn', '[tɑn]'),
  _Syl('tə', '[tœ], [tʉ]'),
  _Syl('təm', '[tʉm]'),
  _Syl('tən', '[tʉn]'),
  _Syl('tə\'', '[tʉʔ]'),
  _Syl('te', '[ti]'),
  _Syl('teb', '[tib]'),
  _Syl('tɛ', '[tɛ]'),
  _Syl('tɛd', '[tɛt]'),
  _Syl('tɛl', '[tɛl]'),
  _Syl('tɛn', '[tɛn]'),
  _Syl('ti', '[tsi]'),
  _Syl('tiα', '[thiɑ]'),
  _Syl('tiαg', '[thiɑk]'),
  _Syl('to', '[tu]'),
  _Syl('tob', '[tub]'),
  _Syl('tod', '[tut]'),
  _Syl('tog', '[tɔk]'),
  _Syl('tol', '[tul]'),
  _Syl('tom', '[tum]'),
  _Syl('ton', '[tun]'),
  _Syl('toŋ', '[tɔŋ]'),
  _Syl('to\'', '[tuʔ]'),
  _Syl('tɔ', '[to]'),
  _Syl('tu', '[thu]'),
  _Syl('tub', '[thub]'),
  _Syl('tud', '[thut]'),
  _Syl('tul', '[thul]'),
  _Syl('tum', '[thum]'),
  _Syl('tun', '[thun]'),
  _Syl('tu\'', '[thuʔ]'),
  _Syl('tʉ', '[thʉ]'),
  _Syl('tʉn', '[thʉn]'),
  _Syl('tʉ\'', '[thʉʔ]'),
  _Syl('tsə', '[tsœ]'),
  _Syl('tsə\'', '[tsœʔ]'),
  _Syl('tsi', '[tsi]'),
  _Syl('tsia', '[tsia]'),
  _Syl('tsiaŋ', '[tsiaŋ]'),
  _Syl('tsiα', '[tsiɑ]'),
  _Syl('tsiαg', '[tsiɑg]'),
  _Syl('tsid', '[tsit]'),
  _Syl('tsil', '[tsil]'),
  _Syl('tsin', '[tsin]'),
  _Syl('tsi\'', '[tsiʔ]'),
  _Syl('tswə', '[tsuœ]'),
  _Syl('u', '[u]'),
  _Syl('və', '[vhœ]'),
  _Syl('vɛ', '[vɛ]'),
  _Syl('vɛn', '[vɛn]'),
  _Syl('vib', '[vib]'),
  _Syl('vog', '[vhɔk]'),
  _Syl('vʉ', '[vhʉ]'),
  _Syl('wa', '[wa]'),
  _Syl('wad', '[wat]'),
  _Syl('wag', '[wak]'),
  _Syl('wal', '[wal]'),
  _Syl('waŋ', '[waŋ]'),
  _Syl('wa\'', '[waʔ]'),
  _Syl('wɛ', '[wɛ]'),
  _Syl('wɛd', '[wɛt]'),
  _Syl('wɛl', '[wɛl]'),
  _Syl('wɛn', '[wɛn]'),
  _Syl('wɔ', '[wo]'),
  _Syl('wu', '[wu]'),
  _Syl('wud', '[wut]'),
  _Syl('wʉ', '[wʉ]'),
  _Syl('nya', '[ɲa]'),
  _Syl('nyad', '[ɲat]'),
  _Syl('nyag', '[ɲak]'),
  _Syl('nyal', '[ɲal]'),
  _Syl('nyam', '[ɲam]'),
  _Syl('nyaŋ', '[ɲaŋ]'),
  _Syl('nya\'', '[ɲaʔ]'),
  _Syl('nyα', '[ɲɑ]'),
  _Syl('nyαm', '[ɲɑm]'),
  _Syl('nyi', '[ɲi]'),
  _Syl('nyid', '[ɲit]'),
  _Syl('nyil', '[ɲil]'),
  _Syl('nyin', '[ɲin]'),
  _Syl('nyi\'', '[ɲiʔ]'),
  _Syl('nyɔ', '[ɲo]'),
  _Syl('nyu', '[ɲu]'),
  _Syl('nyun', '[ɲun]'),
  _Syl('nyu\'', '[ɲuʔ]'),
  _Syl('nywi', '[ɲɥi]'),
  _Syl('nywid', '[ɲɥit]'),
  _Syl('nywil', '[ɲɥil]'),
  _Syl('nywin', '[ɲɥin]'),
  _Syl('nywi\'', '[ɲɥiʔ]'),
  _Syl('ya', '[ja]'),
  _Syl('yad', '[jat]'),
  _Syl('yag', '[jak]'),
  _Syl('yam', '[jam]'),
  _Syl('yaŋ', '[jaŋ]'),
  _Syl('ya\'', '[jaʔ]'),
  _Syl('yα', '[jɑ]'),
  _Syl('yαb', '[jɑb]'),
  _Syl('yαg', '[jɑg]'),
  _Syl('yαm', '[jɑm]'),
  _Syl('yə', '[jʉ]'),
  _Syl('yən', '[jʉn]'),
  _Syl('yə\'', '[jʉʔ]'),
  _Syl('ye', '[ji]'),
  _Syl('yed', '[jit]'),
  _Syl('ye\'', '[jiʔ]'),
  _Syl('yɛ', '[jɛ]'),
  _Syl('yɛn', '[jɛn]'),
  _Syl('yo', '[ju]'),
  _Syl('yob', '[jub]'),
  _Syl('yod', '[jut]'),
  _Syl('yog', '[jɔk]'),
  _Syl('yol', '[jul]'),
  _Syl('yom', '[jum]'),
  _Syl('yoŋ', '[jɔŋ]'),
  _Syl('yo\'', '[juʔ]'),
  _Syl('yu', '[ju]'),
  _Syl('yub', '[jub]'),
  _Syl('ywe', '[jui]'),
  _Syl('ywɛ', '[juɛ]'),
  _Syl('ywɛd', '[juɛt]'),
  _Syl('ywɛl', '[juɛl]'),
  _Syl('ywɛn', '[juɛn]'),
  _Syl('ywi', '[jɥi]'),
  _Syl('ywid', '[jɥit]'),
  _Syl('ywil', '[jɥil]'),
  _Syl('ywim', '[jɥim]'),
  _Syl('ywi\'', '[jɥiʔ]'),
  _Syl('zə', '[zhœ]'),
  _Syl('zə\'', '[zhœʔ]'),
  _Syl('zi', '[zhi]'),
  _Syl('zia', '[zhia]'),
  _Syl('ziag', '[zhiag]'),
  _Syl('zib', '[zhib]'),
  _Syl('zid', '[zhit]'),
  _Syl('zil', '[zhil]'),
  _Syl('zim', '[zhim]'),
  _Syl('zin', '[zhi]'),
  _Syl('zi\'', '[zhiʔ]'),
  _Syl('zwə', '[zhuœ]'),
  _Syl('zwə\'', '[zhuœʔ]'),
  _Syl('zwi', '[zɥi]'),
  _Syl('zwia', '[zɥia]'),
  _Syl('zwiaŋ', '[zɥiaŋ]'),
  _Syl('zwiα', '[zɥiɑ]'),
  _Syl('zwiαg', '[zɥiɑk]'),
  _Syl('zwid', '[zɥit]'),
  _Syl('zwil', '[zɥil]'),
  _Syl('zwim', '[zɥim]'),
  _Syl('zwi\'', '[zɥiʔ]'),
];

const _kPurple = Color(0xFF7C3AED);

class PronunciationScreen extends StatefulWidget {
  const PronunciationScreen({super.key});
  @override
  State<PronunciationScreen> createState() => _PronunciationScreenState();
}

const _kToneKeys = ['bas', 'moyen', 'montant', 'descendant'];
const _kToneLabels = {'bas': 'Bas', 'moyen': 'Moyen', 'montant': 'Montant', 'descendant': 'Descendant'};

class _PronunciationScreenState extends State<PronunciationScreen> {
  String _query = '';
  String? _playingKey; // "<syllable>_<tone>" en cours de lecture

  @override
  void initState() {
    super.initState();
    SyllableAudio.instance.ensureLoaded().then((_) {
      if (mounted) setState(() {});
    });
  }

  @override
  void dispose() {
    MedumbaAudioService.instance.stop();
    super.dispose();
  }

  List<_Syl> get _filtered {
    // Recherche sur la syllabe uniquement (pas l'IPA), comme sur le web.
    if (_query.isEmpty) return _kSyllables;
    final q = _query.toLowerCase();
    return _kSyllables.where((s) => s.syllable.toLowerCase().contains(q)).toList();
  }

  Future<void> _playTone(String syllable, String tone) async {
    final key = '${syllable}_$tone';
    setState(() => _playingKey = key);
    final url = tone == 'neutre'
        ? SyllableAudio.instance.syllableAudioUrl(syllable)
        : SyllableAudio.instance.toneAudioUrl(syllable, tone);
    await MedumbaAudioService.instance.playUrl(url);
    if (mounted) setState(() => _playingKey = null);
  }

  void _openToneSheet(_Syl s) {
    final tons = SyllableAudio.instance.tonsFor(s.syllable);
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setSheetState) => Padding(
          padding: const EdgeInsets.fromLTRB(20, 20, 20, 28),
          child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [
            Row(children: [
              Text(s.syllable, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900, color: kInk)),
              const SizedBox(width: 10),
              Text(s.ipa, style: const TextStyle(fontSize: 14, color: _kPurple, fontStyle: FontStyle.italic)),
            ]),
            const SizedBox(height: 16),
            if (tons == null)
              Text(
                AppLanguage.instance.isFr
                    ? 'Aucun enregistrement pour cette syllabe.'
                    : 'No recording for this syllable.',
                style: const TextStyle(color: kMuted),
              )
            else
              Wrap(
                spacing: 10,
                runSpacing: 10,
                children: _kToneKeys.map((tone) {
                  final char = tons[tone] ?? '';
                  final key = '${s.syllable}_$tone';
                  final playing = _playingKey == key;
                  return InkWell(
                    borderRadius: BorderRadius.circular(14),
                    onTap: () async {
                      setSheetState(() {});
                      await _playTone(s.syllable, tone);
                      setSheetState(() {});
                    },
                    child: Container(
                      width: 130,
                      padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 12),
                      decoration: BoxDecoration(
                        color: playing ? _kPurple.withValues(alpha: 0.1) : const Color(0xFFFAF5FF),
                        border: Border.all(color: playing ? _kPurple : const Color(0xFFE9D5FF), width: 1.5),
                        borderRadius: BorderRadius.circular(14),
                      ),
                      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                        Text(_kToneLabels[tone] ?? tone,
                            style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w700, color: kMuted)),
                        const SizedBox(height: 4),
                        Row(children: [
                          Text(char, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: _kPurple)),
                          const Spacer(),
                          Icon(playing ? Icons.volume_up : Icons.volume_down, size: 18, color: _kPurple),
                        ]),
                      ]),
                    ),
                  );
                }).toList(),
              ),
          ]),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final results = _filtered;
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        title: Text(AppLanguage.instance.isFr ? 'Syllabaire' : 'Syllabary',
            style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 20, color: kInk)),
        actions: [
          Padding(
            padding: const EdgeInsets.fromLTRB(0, 0, 16, 0),
            child: Center(
              child: Text('${results.length} / ${_kSyllables.length}',
                  style: const TextStyle(color: kMuted, fontSize: 13, fontWeight: FontWeight.w600)),
            ),
          ),
        ],
      ),
      body: Column(children: [
        Container(
          color: Colors.white,
          padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
          child: TextField(
            onChanged: (v) => setState(() => _query = v),
            decoration: InputDecoration(
              hintText: AppLanguage.instance.isFr
                  ? 'Rechercher une syllabe…'
                  : 'Search a syllable…',
              prefixIcon: const Icon(Icons.search, color: kMuted),
              filled: true,
              fillColor: const Color(0xFFF1F5F9),
              contentPadding: const EdgeInsets.symmetric(vertical: 0),
              border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
            ),
          ),
        ),
        Expanded(
          child: results.isEmpty
              ? Center(
                  child: Text(AppLanguage.instance.isFr ? 'Aucun résultat' : 'No results',
                      style: const TextStyle(color: kMuted, fontWeight: FontWeight.w600)))
              : ListView.builder(
                  padding: const EdgeInsets.fromLTRB(16, 4, 16, 24),
                  itemCount: results.length,
                  itemBuilder: (_, i) {
                    final s = results[i];
                    final hasRecording = SyllableAudio.instance.hasRecording(s.syllable);
                    return InkWell(
                      borderRadius: BorderRadius.circular(12),
                      onTap: () => _openToneSheet(s),
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 6),
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          border: Border.all(color: kBorder),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Row(children: [
                          SizedBox(
                            width: 80,
                            child: Text(s.syllable,
                                style: const TextStyle(
                                    fontSize: 18, fontWeight: FontWeight.w900, color: kInk)),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(s.ipa,
                                style: const TextStyle(
                                    fontSize: 13,
                                    color: _kPurple,
                                    fontWeight: FontWeight.w600,
                                    fontStyle: FontStyle.italic)),
                          ),
                          Icon(
                            hasRecording ? Icons.volume_up : Icons.volume_off,
                            size: 18,
                            color: hasRecording ? _kPurple : kMuted,
                          ),
                        ]),
                      ),
                    );
                  },
                ),
        ),
      ]),
    );
  }
}
